export const state = {
  message: 'hello vuex',
  snippets: [
    {
      id: 1,
      title: 'Ranking Icon',
      link: 'code1',
      referencLink: {
        name: '',
        url: '',
        image: '',
      },
      codepenId: 'mdyxxpo',
    },
    {
      id: 2,
      title: 'Title Animetion',
      link: 'code2',
      referencLink: {
        name: '',
        url: '',
        image: '',
      },
      codepenId: 'QWwmmBN',
    },
    {
      id: 3,
      title: 'MoreView Card',
      link: 'code3',
      referencLink: '',
      codepenId: 'zYxpqYB',
    },
    {
      id: 4,
      title: 'Project LogoIcon',
      link: 'code4',
      referencLink: '',
      codepenId: 'poJaLPZ',
    },
    {
      id: 5,
      title: 'Entry Button',
      link: 'code5',
      referencLink: {
        name: '株式会社コンテンツワン',
        url: 'https://contents-one.co.jp/',
        image: 'contents-one.png',
      },
      codepenId: 'gOYKvdj',
    },
    {
      id: 6,
      title: 'Icon HoverAnimation',
      link: 'code6',
      referencLink: {
        name: '',
        url: '',
        image: '',
      },
      codepenId: 'drQQmz',
    },
    {
      id: 7,
      title: 'Arrow Button',
      link: 'code7',
      referencLink: {
        name: '',
        url: '',
        image: '',
      },
      codepenId: 'vPjggY',
    },
    {
      id: 8,
      title: 'Password Strength',
      link: 'code8',
      referencLink: {
        name: '',
        url: '',
        image: '',
      },
      codepenId: 'wvaEXgy',
    },
    {
      id: 9,
      title: 'cromier',
      link: 'code9',
      referencLink: {
        name: 'Cromier: Italian Sneakers',
        url: 'https://www.cromier.it/it/',
        image: 'cromier.png',
      },
      codepenId: 'QWbodeV',
    },
    {
      id: 10,
      title: 'Modal',
      link: 'code10',
      referencLink: {
        name: '',
        url: '',
        image: '',
      },
      codepenId: 'QWbaxgp',
    },
    {
      id: 11,
      title: 'Loading Circle',
      link: 'code11',
      referencLink: {
        name: '',
        url: '',
        image: '',
      },
      codepenId: 'BaoNOZG',
    },
    {
      id: 12,
      title: 'DrawerMenu TouchMove',
      link: 'code12',
      referencLink: {
        name: '',
        url: '',
        image: '',
      },
      codepenId: 'PoPzOQY',
    },
    {
      id: 13,
      title: 'CardContent',
      link: 'code13',
      referencLink: {
        name: '大成紙器製作所',
        url: 'https://www.taisei-shiki.jp/',
        image: 'taisei-shiki.png',
      },
      codepenId: 'NWGyWWo',
    },
    {
      id: 14,
      title: 'Particles',
      link: 'code14',
      referencLink: {
        name: 'particles.js',
        url: 'https://vincentgarreau.com/particles.js/',
        image: 'particles.png',
      },
      codepenId: 'dLmzbK',
    },
    {
      id: 15,
      title: 'AutoKana',
      link: 'code15',
      referencLink: {
        name: '',
        url: '',
        image: '',
      },
      codepenId: 'rEyBKJ',
    },
    {
      id: 16,
      title: 'Mask Animation',
      link: 'code16',
      referencLink: {
        name: '',
        url: '',
        image: '',
      },
      codepenId: 'GRpaBay',
    },
    {
      id: 17,
      title: 'Movie Button',
      link: 'code17',
      referencLink: {
        name: 'UNIEL ltd. RECRUIT SITE Second Face',
        url: 'https://recruit.uniel.jp/',
        image: 'uniel-recruit.png',
      },
      codepenId: 'qBbRvXK',
    },
    {
      id: 18,
      title: 'Outline Button',
      link: 'code18',
      referencLink: {
        name: 'UNIEL ltd. RECRUIT SITE Second Face',
        url: 'https://recruit.uniel.jp/',
        image: 'uniel-recruit.png',
      },
      codepenId: 'rNxjbmq',
    },
    {
      id: 19,
      title: 'Hubble Title',
      link: 'code19',
      referencLink: {
        name: 'Hubble | 契約書の管理・共有をスマートにするソフトウェア',
        url: 'https://hubble-docs.com/',
        image: 'hubble-docs.png',
      },
      codepenId: 'zYqEaev',
    },
  ],
}
