version: 2.1
executors:
  default:
    working_directory: ~/workspace
    docker:
      - image: node:14
commands:
  restore_npm:
    steps:
      - restore_cache:
          name: Restore npm dependencies
          key: npm-{{ checksum "package.json" }}

  save_npm:
    steps:
      - save_cache:
          name: Cache npm dependencies
          key: npm-{{ checksum "package.json" }}
          paths:
            - ~/workspace/node_modules
jobs:
  setup:
    executor:
      name: default
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn install
      - save_npm
  lint:
    executor:
      name: default
    steps:
      - checkout
      - restore_npm
      - run:
          name: Lint
          command: yarn lint
      - save_npm
  generate:
    executor:
      name: default
    steps:
      - checkout
      - restore_npm
      - run:
          name: Generate
          command: yarn generate
      - save_npm
workflows:
  pull-request:
    jobs:
      - setup
      - lint:
          requires:
            - setup
      - generate:
          requires:
            - lint